# Generated by Django 4.2.13 on 2024-09-13 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ф.И.О.')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='комментарий')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='тело письма')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'сообщение рассылки',
                'verbose_name_plural': 'сообщения рассылок',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start_mailing', models.DateTimeField(auto_now_add=True, verbose_name='дата начала рассылки')),
                ('date_next_mailing', models.DateTimeField(blank=True, null=True, verbose_name='дата следующей рассылки')),
                ('date_end_mailing', models.DateTimeField(blank=True, null=True, verbose_name='дата окончания рассылки')),
                ('periodicity_mailing', models.CharField(choices=[('minute', 'раз в минуту'), ('hour', 'раз в часа'), ('day', 'раз в день'), ('week', 'раз в неделю'), ('month', 'раз в месяц'), ('year', 'раз в год')], default='minute', max_length=6, verbose_name='периодичность')),
                ('mailing_status', models.CharField(choices=[('created', 'создана'), ('started', 'запущена'), ('completed', 'выполнена'), ('error', 'ошибка')], default='created', max_length=15, verbose_name='статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='активация рассылки')),
                ('clients', models.ManyToManyField(to='mailing.client', verbose_name='Кому (клиенты сервиса)')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingmessage', verbose_name='Сообщение')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'настройка рассылки',
                'verbose_name_plural': 'настройки рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_try_last', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('try_status', models.BooleanField(default=False, verbose_name='статус попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsettings', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'попытка рассылки',
                'verbose_name_plural': 'попытки рассылки',
            },
        ),
    ]
